import { Website } from "@/app/global/svg";
import { usePageContext } from "@/components/Providers/PageContext";

export default function Head() {
  const { i18 } = usePageContext();
  return (
    <>
      <title>
        {i18?.ACCOUNTINFO?.HOSTYOURHOMEON || "Host your home on "}
        <Website />
      </title>
      <meta content="width=device-width, initial-scale=1" name="viewport" />
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </>
  );
}
