export default class APICONSTANT {
  static readonly signup = 'auth/user'
  static readonly login = 'auth/user/login'
  static readonly sentOTP = 'auth/user/sendOtp'
  static readonly verifyOTP = 'auth/user/verifyOtp'
  static readonly forgetPassword = 'auth/user/forgetPassword'
  static readonly setPassword = 'auth/user/setPassword'
  static readonly listinfo = 'listing/info'  
  static readonly pendingList = `listing/pending`
  static readonly basicdetails = `listing/basicDetails`
  static readonly coverImage = `listing/coverImage`
  static readonly groupImage = `listing/groupImage`
  static readonly completeSetup = `listing/update/status`
  static readonly addPrice = `listing/price`
  static readonly propertyCategory = `listing/categories`
  static readonly adsCategory = `ads/categories`
  static readonly privacyType = `listing/properties`
  static readonly counts = `listing/todayMenu`
  static readonly publish = `listing/publish`
  static readonly placesOffer = `listing/amentity`
  static readonly privileges = `listing/privileges`
  static readonly privilegesItems = `listing/privilegesItems`
  static readonly Amenity = `listing/amenities`
  static readonly getListing = `listing`
  static readonly cancellationPolicy = `listing/cancellationPolicy`
  static readonly icon = `user/icon`
  static readonly availability = `listing/availability`
  static readonly getSteps = `listing/getSteps`
  static readonly rules = `listing/rules`
  static readonly estimation = `listing/booking/estimation`
  static readonly googleLogin = `https://oauth2.googleapis.com/token`
  static readonly wishList = `listing/wishList`
  static readonly wishlistCollection = `listing/wishList`
  static readonly listComplete = `listing/booking/complete`
  static readonly pendingBooking = `listing/booking/pending`
  static readonly confirmBooking = `listing/booking/confirm`
  static readonly acceptedBooking = `listing/booking/accepted`
  static readonly cancelBooking = `listing/booking/cancel`
  static readonly hostListings = `listing/userListings`
  static readonly calenderListings = `listing/listingAvailability`
  static readonly reviewRating = `listing/reviewsAndRating`
  static readonly getreviewRating = `listing/viewUserReview`
  static readonly blockedDates = `listing/blockDates`
  static readonly calendarDates = `calendar/records`
  // static readonly booking = `listing/booking`
  // static readonly paymentStatus = `payment/status`
  static readonly booking = `listing/initiateBooking`
  static readonly paymentStatus = `listing/paymentStatus`
  static readonly getproperties = `listing/properties`
  static readonly getadsproperties = `ads/subCategories`
  static readonly burgerCount = `chat/burgerCount`
  static readonly chat = `chat`
  static readonly chatinfo = `chat/chatInfo`
  static readonly adschatinfo = `chat/adsChatInfo`
  static readonly chatblock = `chat/block`
  static readonly chatdelete = `chat/deleteChat`
  static readonly messagedelete = `chat/deleteMessage`
  static readonly messagedeleteall = `chat/deleteMultipleMessage`   
  static readonly chatList = `chat/list`
  static readonly blockedList = `chat/list?status=blocked`
  static readonly approvedListings = `listing/detail`
  static readonly approvedadsListings = `ads/detail`
  static readonly notifications = `notifications`
  static readonly currentBooking =`listing/booking/current`
  static readonly bookingHistory =`listing/booking/history`
  static readonly cancelledBooking =`listing/booking/cancelled`
  static readonly bookingApproval =`listing/booking/approval`
  static readonly upcommingBooking =`listing/booking/upcomming`
  static readonly language = `translation/languages/user`
  static readonly hostdetails = `auth/user/Details`
  static readonly HostListings = `auth/user/listings`
  static readonly userExist = 'auth/user/exists'
  static readonly changepassword = 'auth/user/password/'
  static readonly transaction = `wallet/history`
  static readonly addBank = `wallet/bank`
  static readonly sendEmail = `auth/user/sendOtpByEmail`
  static readonly verifyEmail = `auth/user/verifyOtpByEmail`
  static readonly verifyKey = `auth/user/verifyKey`
  static readonly resetPassword = `auth/user/setPassword`
  static readonly cms = 'cms'
  static readonly settings = 'settings'
  static readonly Translation ='translation/translatejson'
  static readonly locale ='locale/en.json'
  static readonly payoutAount = 'wallet/payout'
  static readonly getpayout = 'wallet/payoutHistory'
  static readonly getdocument = 'document/user'
  static readonly recaptcha = 'auth/recaptcha'
  static readonly reportListing = 'report/listing'
  static readonly reportTitle = 'report/reportTitle'
  static readonly reportDesc = 'report/description'
   static readonly Gallery = 'gallery/images'
   static readonly howdoesworks = `admin/howItWorks/`
   static readonly bookingCount = `listing/booking/count/`
   static readonly cmsList = `cms`
  //  ADS API'S
   static readonly packageStatus = `ads/packageStatus`
   static readonly packageDatas = `ads/packages`
   static readonly packagesSubscription = `ads/subscribe/package`
   static readonly adsPaymentStatus = `ads/verify/payment`
   static readonly subscriptionStatus = `ads/user/packages`
}
