// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChJYalTQLfafkas1Vk7FCHKQRemWPcBEU',
    appId: '1:411258942751:web:c855b48cada5d46425ec2a',
    messagingSenderId: '411258942751',
    projectId: 'airstar-7fbc3',
    authDomain: 'airstar-7fbc3.firebaseapp.com',
    databaseURL: 'https://airstar-7fbc3.firebaseio.com',
    storageBucket: 'airstar-7fbc3.firebasestorage.app',
    measurementId: 'G-PREEERW3VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxvNMqKCw-ikep_FW4Xtg7GTPuh6oO8cc',
    appId: '1:411258942751:android:c72245b6468d5fb625ec2a',
    messagingSenderId: '411258942751',
    projectId: 'airstar-7fbc3',
    databaseURL: 'https://airstar-7fbc3.firebaseio.com',
    storageBucket: 'airstar-7fbc3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBRHkm4mv_CYgw97N2qUDhWEBrPrKQfUY',
    appId: '1:411258942751:ios:5990d939d4d2505425ec2a',
    messagingSenderId: '411258942751',
    projectId: 'airstar-7fbc3',
    databaseURL: 'https://airstar-7fbc3.firebaseio.com',
    storageBucket: 'airstar-7fbc3.firebasestorage.app',
    androidClientId: '411258942751-60a3oa0vs85nfbjqluhtoilhjmju40dl.apps.googleusercontent.com',
    iosClientId: '411258942751-6uhnqt0ci1p9of385hg22m87ck2grhet.apps.googleusercontent.com',
    iosBundleId: 'com.abserve.tech.airstar',
  );

}